### ISSUE TITLE
Seqfaults immediatly after dialogue about downloading news

### ISSUE THREAD

**Issue by onlyjob** [wxLauncher/wxlauncher#116]
As originally reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=770855
Wxlauncher segfaults on (first) start after "retrieve latest news {Yes} {No}" dialog, when button "No" is clicked:

~~~~
Program received signal SIGSEGV, Segmentation fault.
0x0000000000526fa0 in wxLauncher::OnInit (this=<optimized out>) at /mnt/tmpssd/src/wxlauncher/wxlauncher-release-0.9.5/code/wxLauncherApp.cpp:251
251             splashWindow->Show(false);
(gdb) thread apply all bt

Thread 1 (Thread 0x7ffff7f79a40 (LWP 32054)):
#0  0x0000000000526fa0 in wxLauncher::OnInit (this=<optimized out>) at /mnt/tmpssd/src/wxlauncher/wxlauncher-release-0.9.5/code/wxLauncherApp.cpp:251
#1  0x00007ffff7a2cc42 in wxEntry (argc=@0x7ffff7dd78f0: 1, argv=<optimized out>) at ../src/common/init.cpp:479
Segmentation fault
~~~~

Reproduced on 0.9.6 built with "-DNDEBUG". 

When built without "-DNDEBUG" I'm getting the following run-time segfault on second start when `~/.wxlauncher/global.ini` exists:

~~~~
ASSERT INFO:
/usr/include/wx-3.0/wx/strvararg.h(456): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type

BACKTRACE:
[1] wxArgNormalizer /usr/include/wx-3.0/wx/strvararg.h:456
[2] wxLauncher::OnInit() /mnt/tmpssd/src/wxlauncher/wxlauncher-release-0.9.5/code/wxLauncherApp.cpp:219
[3] wxEntry(int&, wchar_t**)
[4] main /mnt/tmpssd/src/wxlauncher/wxlauncher-release-0.9.5/code/wxLauncherApp.cpp:50
[5] __libc_start_main
[6] _start
~~~~

I can only use `wxlauncher` built with "-DNDEBUG" and only if I manually add 

~~~~
[net]
downloadnews=0
~~~~

to `~/.wxlauncher/global.ini`.

**Comment by IssMneur** [comment]
I have pushed da9cda2 to my personal fork.  This seems to resolve the issue on Debian Jessie for me.

**Comment by onlyjob** [comment]
It fixes the problem, thanks.
